appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ITyPicgsY7XZqsVwtoXpCIi5h3/t1lQFEk9Mevt5QzyeV95txPw9KCpt9iDhNuEfCFDFmVAO1okgeNrUnJ/0cFkDkeLgGpEvYpA2HuwE+EZvcIYyE4GHM5Pl0slKPOLqDforbICgPqRWaa0miNlYN7aPXq6RIUPyDV1IND13dDtTfKvLvKeyI4r7PaCK+8iYFXykxg8fzDEaeDMGmtv9Sd1cssgYYIB38L6+fgUiKIecbLU6vVPrGoFL6eBKvrbbjI7D3rJw7B/zzyARn/ZKh6jaqnJxL8oLUaz/bkO0W3M+jfUCSxhIzLtZo6iFeVUxl1vq+Zpc6U4NwHmqbXtrOngszjY+cRdcnQTqvv46JYCJFNfuekGYnqGgzGCbZZYk8RJeEp/cwIgKzjmsIpy0PAtRrIoOU6yxUpEv7sP2w7paDtwAHdBdpraXXLlsJpV+2W0mDL9zCf/Lu8PQMHiD8NNoZ//4oKLZIvjWIW7c7II0E6dIHV6Q0Q8/LiLByA2OJTR1c6lIeOfJGV2ly8bwR2wNZVnBw+CIgsN+e0uPuLmtgu8+oPf2bAAP9IuSoLwG7PZMYUfqTPNTnGr36MPhtp1t0u5r6iCoI4D7i9+Ex3/H2vnDJpi7fqEc8BbQIvShc3SSkootRZHLXINoWnPekjuK6qc3Dsr1H4k6i1+dxlo=}
