travis:
  secure:
    BINSTAR_TOKEN: u0sbDZScX1WdjtnKiDZN+iNJgOWYet0tLPUPSR5nwIoS88XYI+9eRSe35uWTBxPPn2TW4hA6iaxFaAG5zv+lewr7vLsDXSLuajxDQFf0Agf5mww1HQ6+LdK9D8MoglKRNzAi5t6O8vlENaNIybwIx2gtiFBjzYW8Uie8sCXOQgOCzecwr/naTCO0ZrDL22YTxXAxzwTyRB9hK92EeOXCLWlSl4ACi0a6aNWcUxNNg69YrXxwrYw86krIh/j07voX1g4fcGin31zQupbqNQW/p1VF3cwEDS427WKtoyymz1xsU5BuOK6V1bVs7a45koivqQlRvXWqx88ABbZ58mp2eHcBmM7CqiVUdv+QS4292IyXWOlsJ7gW4hcmxW6yDyluRrCNNoCbsn83BHOfJqFEEJX4j+DK3932UM28/rnMHwHquA3s8lyFrtMeVcLmWh1bGQPSGctRQT5c+/Ko5HxaJQmR3q9AoKDIOiNnV3uMuWcYpr8yBsWQK6PeyrgcYwU7HFtoKSuNeQHdY5eH7Y8F/uBdFZGmMBNnTtWKTLUZqaALTjFEox4W9s1lXc4VUew3KnZye/wrKol2ocSDR5/eKtNyUlqQkI7L92//tbqk/iUXl42n80NbcrCgED+FSo1BGr7qfDD3JQajBk0yM2ZjMz+RvNTE6oZZvs/I2hk+yFE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
